import React from "react";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { ClientLayout } from "@/component/layout/ClientLayout";
import I18nProvider from "./providers/i18nProvider"; // <- use this client provider
import { AuthProvider } from "./providers/authProvider";


export const metadata: Metadata = {
  title: "Offical SkyLink website ",
  description: "Generated by create next app",
  icons: {
    icon: '/globe.svg'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
          <I18nProvider>
              <AuthProvider>
                <ClientLayout>{children}</ClientLayout>
              </AuthProvider>
          </I18nProvider>
      </body>
    </html>
  );
}
