import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientLayout } from "@/component/layout/ClientLayout";
import I18nProvider from "./providers/i18nProvider"; // <- use this client provider


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Offical SkyLink website ",
  description: "Generated by create next app",
  icons: {
    icon: '/globe.svg'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <I18nProvider>
            <ClientLayout>{children}</ClientLayout>
          </I18nProvider>
      </body>
    </html>
  );
}
